resources:
  - ../../common
  - ../../common/node-exporter
  - ../../common/kube-state-metrics
  - ../../common/opentelemetry-operator
  - ./logcol.yaml
  - ./telemetrygw.yaml
  # - ./targetallocator.yaml
  - ./rbac.yaml
  # - ./servicemonitor.yaml
