apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector-with-ta
  namespace: monitoring
  labels:
    opentelemetry.io/target-allocator: targetallocator
spec:
  mode: statefulset
  image: "otel/opentelemetry-collector-contrib:0.154.0"
  ports:
    - name: metrics
      port: 8888
      targetPort: 8888
  config:
    receivers:
      prometheus:
        config:
          # Target Allocator will dynamically inject scrape configurations here
          scrape_configs: []

    exporters:
      debug: {}
      prometheusremotewrite:
        endpoint: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [debug, prometheusremotewrite]
