# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/opentelemetry.io/targetallocator_v1alpha1.json
apiVersion: opentelemetry.io/v1alpha1
kind: TargetAllocator
metadata:
  name: targetallocator
  namespace: monitoring
spec:
  allocationStrategy: consistent-hashing
  prometheusCR:
    enabled: true
    serviceMonitorSelector:
      matchLabels:
        release: local
    podMonitorSelector:
      matchLabels:
        release: local
