# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/opentelemetry.io/opentelemetrycollector_v1beta1.json
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: telemetry-gateway
  namespace: monitoring
  labels:
    opentelemetry.io/target-allocator: targetallocator
spec:
  mode: statefulset
  serviceAccount: telemetry-gateway
  replicas: 3
  volumeClaimTemplates:
    - metadata:
        name: file-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
  volumeMounts:
    - name: file-storage
      mountPath: /var/lib/storage/otc
  image: "otel/opentelemetry-collector-contrib:0.154.0"
  ports:
    - name: metrics
      port: 8888
      targetPort: 8888
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  config:
    extensions:
      file_storage:
        directory: /var/lib/storage/otc
        timeout: 10s
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      transform/containers_parse_json:
        error_mode: ignore
        log_statements:
          - context: log
            statements:
              - set(body, ParseJSON(body)) where IsMatch(body, "^{")
      transform/flatten:
        error_mode: ignore
        log_statements:
          - context: log
            statements:
              - merge_maps(attributes, body, "insert") where IsMap(body)
              - set(body, "") where IsMap(body)
      transform/add_timestamp:
        log_statements:
          - context: log
            statements:
              - set(time, Now()) where time_unix_nano == 0
              - set(attributes["timestamp"], Int(time_unix_nano / 1000000))
      resource_detection:
        detectors: [env, system]
        timeout: 2s
        override: false
      k8s_attributes:
        auth_type: serviceAccount
        extract:
          annotations:
            - from: pod
              key_regex: (.*)
              tag_name: pod_annotations_$$1
            - from: namespace
              key_regex: (.*)
              tag_name: namespace_annotations_$$1
            - from: node
              key_regex: (.*)
              tag_name: node_annotations_$$1
          labels:
            - from: pod
              key_regex: (.*)
              tag_name: pod_labels_$$1
            - from: namespace
              key_regex: (.*)
              tag_name: namespace_labels_$$1
            - from: node
              key_regex: (.*)
              tag_name: node_labels_$$1
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.pod.hostname
            - k8s.deployment.name
            - k8s.daemonset.name
            - k8s.replicaset.name
            - k8s.statefulset.name
            - k8s.namespace.name
            - k8s.node.name
            - service.name
            - service.namespace
        passthrough: false
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: resource_attribute
                name: k8s.namespace.name
              - from: resource_attribute
                name: k8s.pod.name
        wait_for_metadata: true
        wait_for_metadata_timeout: 10s
      resource/cluster:
        attributes:
          - action: upsert
            key: cluster
            value: dev-application
      transform/demo:
        error_mode: ignore
        log_statements:
          - context: log
            statements:
              - replace_pattern(log.body, "password=[a-zA-Z0-9]+", "password=***")
      groupbyattrs/containers:
        keys:
          - k8s.container.id
          - k8s.container.name
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.pod.uid
          - cluster
      batch:
        send_batch_size: 1000
        timeout: 10s
    exporters:
      debug: {}
      # Forwarding to the Monitoring Cluster Gateway via NodePort
      otlp/monitoring_cluster:
        endpoint: "host.docker.internal:30431"
        tls:
          insecure: true
        sending_queue:
          enabled: true
          storage: file_storage
        retry_on_failure:
          enabled: true
    service:
      extensions: [file_storage]
      pipelines:
        logs:
          receivers: [otlp]
          processors:
            [
              memory_limiter,
              transform/containers_parse_json,
              transform/flatten,
              transform/add_timestamp,
              resource_detection,
              k8s_attributes,
              resource/cluster,
              transform/demo,
              groupbyattrs/containers,
              batch,
            ]
          exporters: [debug, otlp/monitoring_cluster]
        # Ignoring metrics and traces for now as requested
