resources:
  - ../../common
  - ./telemetry-gateway.yaml

helmCharts:
  - name: sumologic-gateway
    releaseName: sumologic
    version: 4.14.0
    repo: https://sumologic.github.io/sumologic-kubernetes-collection
    namespace: monitoring
    valuesFile: value/sumologic.yaml
