apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: telemetry-gateway
  namespace: monitoring
spec:
  mode: statefulset
  image: "otel/opentelemetry-collector-contrib:0.154.0"
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 1000
        timeout: 10s
    exporters:
      debug: {}
      otlp/sumologic:
        endpoint: "sumologic-gateway-collector.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlp/sumologic]
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-gateway-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: monitoring-gateway-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      nodePort: 30431
      protocol: TCP
